/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'AndrewLevandoski' at '10/23/17 1:13 PM' with Gradle 2.14
 *
 * @author AndrewLevandoski, @date 10/23/17 1:13 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
