import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'AndrewLevandoski' at '10/23/17 1:13 PM' with Gradle 2.14
 *
 * @author AndrewLevandoski, @date 10/23/17 1:13 PM
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        assertEquals(15, Main.triangle(5));
    }
}
